### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wilsoncai1992** [nhejazi/biotmle#1]
- [x] Finish multilevel TMLE-LIMMA algorithm
- [x] collect data + try the method
- [x] include satisfactory data into package
- [x] completion/submission of statistical manuscript
- [x] submission to [JOSS](http://joss.theoj.org)

**Comment by nhejazi** [comment]
@wilsoncai1992, @ahubb40 -- the above are all complete now; please see Overleaf repo for further developments of statistical manuscript. Closing this issue due to completion; feel free to re-open if anything is still unfinished.
